export const testimonials = [
  {
    name: 'Jessica Taylor',
    picture: 'https://randomuser.me/api/portraits/women/7.jpg',
    say: 'This service completely transformed how we handle PR. Our story is now being shared across major outlets.',
    business_position: 'Founder of UrbanLeaf',
  },
  {
    name: 'Matthew Johnson',
    picture: 'https://randomuser.me/api/portraits/men/7.jpg',
    say: 'Connecting with top-tier journalists has never been easier. This platform is a must-have for any startup.',
    business_position: 'CEO at BuildBright',
  },
  {
    name: 'Ashley Thompson',
    picture: 'https://randomuser.me/api/portraits/women/8.jpg',
    say: 'The user-friendly interface and powerful tools helped us achieve media attention like never before.',
    business_position: 'Marketing Manager at GlowTech',
  },
  {
    name: 'Ryan Walker',
    picture: 'https://randomuser.me/api/portraits/men/8.jpg',
    say: 'We saw instant results in our brand awareness after just a few weeks of using this service.',
    business_position: 'Founder of PeakInnovations',
  },
  {
    name: 'Sophia Adams',
    picture: 'https://randomuser.me/api/portraits/women/9.jpg',
    say: 'I can’t believe how much easier it is to gain media coverage with this platform. Truly groundbreaking!',
    business_position: 'CMO at TrendSetters',
  },
  {
    name: 'Ethan Carter',
    picture: 'https://randomuser.me/api/portraits/men/9.jpg',
    say: 'It’s been a game-changer for our business growth. The media exposure was far beyond what we expected.',
    business_position: 'Co-Founder of FutureTech Labs',
  },
  {
    name: 'Megan Parker',
    picture: 'https://randomuser.me/api/portraits/women/10.jpg',
    say: 'The team’s support and platform tools have been exceptional. We’ve reached audiences we never thought possible.',
    business_position: 'VP of Public Relations at CleanEnergyNow',
  },
  {
    name: 'William Davis',
    picture: 'https://randomuser.me/api/portraits/men/10.jpg',
    say: 'This is the best investment we’ve made for our brand. The impact has been tremendous!',
    business_position: 'Founder of FreshlyTech',
  },
  {
    name: 'Hannah Miller',
    picture: 'https://randomuser.me/api/portraits/women/11.jpg',
    say: 'From local exposure to national media, this platform delivered exactly what we needed.',
    business_position: 'Director of Communications at GreenFuture',
  },
  {
    name: 'Benjamin Scott',
    picture: 'https://randomuser.me/api/portraits/men/11.jpg',
    say: 'Our company has seen unparalleled growth in credibility and visibility. Highly recommend this platform.',
    business_position: 'CEO of BrightPath Solutions',
  },
  {
    name: 'Emily Cooper',
    picture: 'https://randomuser.me/api/portraits/women/12.jpg',
    say: 'We’ve expanded our reach significantly since using this service. It’s been a key tool for our growth.',
    business_position: 'CEO at EcoSphere',
  },
  {
    name: 'Liam Roberts',
    picture: 'https://randomuser.me/api/portraits/men/12.jpg',
    say: 'Our team saved countless hours on PR while achieving incredible results. Highly efficient and effective.',
    business_position: 'Founder of BlueHorizon',
  },
  {
    name: 'Abigail Morgan',
    picture: 'https://randomuser.me/api/portraits/women/13.jpg',
    say: 'The results exceeded our expectations. We’re now featured regularly in industry publications.',
    business_position: 'VP of Marketing at ClearTech',
  },
  {
    name: 'Jackson Reed',
    picture: 'https://randomuser.me/api/portraits/men/13.jpg',
    say: 'This platform gave us the edge we needed to stand out in a crowded market.',
    business_position: 'CMO at BrightIdeas',
  },
  {
    name: 'Charlotte Turner',
    picture: 'https://randomuser.me/api/portraits/women/14.jpg',
    say: 'The ability to connect directly with media outlets has transformed how we share our story.',
    business_position: 'Public Relations Manager at GreenWave',
  },
  {
    name: 'Mason Hughes',
    picture: 'https://randomuser.me/api/portraits/men/14.jpg',
    say: 'We’ve seen a huge boost in traffic and engagement thanks to the media coverage we’ve received.',
    business_position: 'Founder of TechBridge',
  },
  {
    name: 'Ava Ramirez',
    picture: 'https://randomuser.me/api/portraits/women/15.jpg',
    say: 'It’s an incredible feeling to see our brand recognized on major platforms. This tool made it happen.',
    business_position: 'Creative Director at InspireCo',
  },
  {
    name: 'Logan Mitchell',
    picture: 'https://randomuser.me/api/portraits/men/15.jpg',
    say: 'From day one, we’ve seen immediate results in our PR campaigns. Couldn’t be happier.',
    business_position: 'Co-Founder of UrbanNest',
  },
  {
    name: 'Grace Walker',
    picture: 'https://randomuser.me/api/portraits/women/16.jpg',
    say: 'This platform is a PR powerhouse! It’s simple, effective, and produces real results.',
    business_position: 'CEO of BrightWorks',
  },
  {
    name: 'Ethan Harris',
    picture: 'https://randomuser.me/api/portraits/men/16.jpg',
    say: 'We’ve reached more people in the last month than we did in the past year. Truly outstanding!',
    business_position: 'Head of Marketing at FutureWave',
  },
  {
    name: 'Jessica Taylor',
    picture: 'https://randomuser.me/api/portraits/women/7.jpg',
    say: 'This service completely transformed how we handle PR. Our story is now being shared across major outlets.',
    business_position: 'Founder of UrbanLeaf',
  },
  {
    name: 'Matthew Johnson',
    picture: 'https://randomuser.me/api/portraits/men/7.jpg',
    say: 'Connecting with top-tier journalists has never been easier. This platform is a must-have for any startup.',
    business_position: 'CEO at BuildBright',
  },
  {
    name: 'Ashley Thompson',
    picture: 'https://randomuser.me/api/portraits/women/8.jpg',
    say: 'The user-friendly interface and powerful tools helped us achieve media attention like never before.',
    business_position: 'Marketing Manager at GlowTech',
  },
  {
    name: 'Ryan Walker',
    picture: 'https://randomuser.me/api/portraits/men/8.jpg',
    say: 'We saw instant results in our brand awareness after just a few weeks of using this service.',
    business_position: 'Founder of PeakInnovations',
  },
  {
    name: 'Sophia Adams',
    picture: 'https://randomuser.me/api/portraits/women/9.jpg',
    say: 'I can’t believe how much easier it is to gain media coverage with this platform. Truly groundbreaking!',
    business_position: 'CMO at TrendSetters',
  },
  {
    name: 'Ethan Carter',
    picture: 'https://randomuser.me/api/portraits/men/9.jpg',
    say: 'It’s been a game-changer for our business growth. The media exposure was far beyond what we expected.',
    business_position: 'Co-Founder of FutureTech Labs',
  },
  {
    name: 'Megan Parker',
    picture: 'https://randomuser.me/api/portraits/women/10.jpg',
    say: 'The team’s support and platform tools have been exceptional. We’ve reached audiences we never thought possible.',
    business_position: 'VP of Public Relations at CleanEnergyNow',
  },
  {
    name: 'William Davis',
    picture: 'https://randomuser.me/api/portraits/men/10.jpg',
    say: 'This is the best investment we’ve made for our brand. The impact has been tremendous!',
    business_position: 'Founder of FreshlyTech',
  },
  {
    name: 'Hannah Miller',
    picture: 'https://randomuser.me/api/portraits/women/11.jpg',
    say: 'From local exposure to national media, this platform delivered exactly what we needed.',
    business_position: 'Director of Communications at GreenFuture',
  },
  {
    name: 'Benjamin Scott',
    picture: 'https://randomuser.me/api/portraits/men/11.jpg',
    say: 'Our company has seen unparalleled growth in credibility and visibility. Highly recommend this platform.',
    business_position: 'CEO of BrightPath Solutions',
  },
  {
    name: 'Emily Cooper',
    picture: 'https://randomuser.me/api/portraits/women/12.jpg',
    say: 'We’ve expanded our reach significantly since using this service. It’s been a key tool for our growth.',
    business_position: 'CEO at EcoSphere',
  },
  {
    name: 'Liam Roberts',
    picture: 'https://randomuser.me/api/portraits/men/12.jpg',
    say: 'Our team saved countless hours on PR while achieving incredible results. Highly efficient and effective.',
    business_position: 'Founder of BlueHorizon',
  },
  {
    name: 'Abigail Morgan',
    picture: 'https://randomuser.me/api/portraits/women/13.jpg',
    say: 'The results exceeded our expectations. We’re now featured regularly in industry publications.',
    business_position: 'VP of Marketing at ClearTech',
  },
  {
    name: 'Jackson Reed',
    picture: 'https://randomuser.me/api/portraits/men/13.jpg',
    say: 'This platform gave us the edge we needed to stand out in a crowded market.',
    business_position: 'CMO at BrightIdeas',
  },
  {
    name: 'Charlotte Turner',
    picture: 'https://randomuser.me/api/portraits/women/14.jpg',
    say: 'The ability to connect directly with media outlets has transformed how we share our story.',
    business_position: 'Public Relations Manager at GreenWave',
  },
  {
    name: 'Mason Hughes',
    picture: 'https://randomuser.me/api/portraits/men/14.jpg',
    say: 'We’ve seen a huge boost in traffic and engagement thanks to the media coverage we’ve received.',
    business_position: 'Founder of TechBridge',
  },
  {
    name: 'Ava Ramirez',
    picture: 'https://randomuser.me/api/portraits/women/15.jpg',
    say: 'It’s an incredible feeling to see our brand recognized on major platforms. This tool made it happen.',
    business_position: 'Creative Director at InspireCo',
  },
  {
    name: 'Logan Mitchell',
    picture: 'https://randomuser.me/api/portraits/men/15.jpg',
    say: 'From day one, we’ve seen immediate results in our PR campaigns. Couldn’t be happier.',
    business_position: 'Co-Founder of UrbanNest',
  },
  {
    name: 'Grace Walker',
    picture: 'https://randomuser.me/api/portraits/women/16.jpg',
    say: 'This platform is a PR powerhouse! It’s simple, effective, and produces real results.',
    business_position: 'CEO of BrightWorks',
  },
  {
    name: 'Ethan Harris',
    picture: 'https://randomuser.me/api/portraits/men/16.jpg',
    say: 'We’ve reached more people in the last month than we did in the past year. Truly outstanding!',
    business_position: 'Head of Marketing at FutureWave',
  },
  {
    name: 'Jessica Taylor',
    picture: 'https://randomuser.me/api/portraits/women/7.jpg',
    say: 'This service completely transformed how we handle PR. Our story is now being shared across major outlets.',
    business_position: 'Founder of UrbanLeaf',
  },
  {
    name: 'Matthew Johnson',
    picture: 'https://randomuser.me/api/portraits/men/7.jpg',
    say: 'Connecting with top-tier journalists has never been easier. This platform is a must-have for any startup.',
    business_position: 'CEO at BuildBright',
  },
  {
    name: 'Ashley Thompson',
    picture: 'https://randomuser.me/api/portraits/women/8.jpg',
    say: 'The user-friendly interface and powerful tools helped us achieve media attention like never before.',
    business_position: 'Marketing Manager at GlowTech',
  },
  {
    name: 'Ryan Walker',
    picture: 'https://randomuser.me/api/portraits/men/8.jpg',
    say: 'We saw instant results in our brand awareness after just a few weeks of using this service.',
    business_position: 'Founder of PeakInnovations',
  },
  {
    name: 'Sophia Adams',
    picture: 'https://randomuser.me/api/portraits/women/9.jpg',
    say: 'I can’t believe how much easier it is to gain media coverage with this platform. Truly groundbreaking!',
    business_position: 'CMO at TrendSetters',
  },
  {
    name: 'Ethan Carter',
    picture: 'https://randomuser.me/api/portraits/men/9.jpg',
    say: 'It’s been a game-changer for our business growth. The media exposure was far beyond what we expected.',
    business_position: 'Co-Founder of FutureTech Labs',
  },
  {
    name: 'Megan Parker',
    picture: 'https://randomuser.me/api/portraits/women/10.jpg',
    say: 'The team’s support and platform tools have been exceptional. We’ve reached audiences we never thought possible.',
    business_position: 'VP of Public Relations at CleanEnergyNow',
  },
  {
    name: 'William Davis',
    picture: 'https://randomuser.me/api/portraits/men/10.jpg',
    say: 'This is the best investment we’ve made for our brand. The impact has been tremendous!',
    business_position: 'Founder of FreshlyTech',
  },
  {
    name: 'Hannah Miller',
    picture: 'https://randomuser.me/api/portraits/women/11.jpg',
    say: 'From local exposure to national media, this platform delivered exactly what we needed.',
    business_position: 'Director of Communications at GreenFuture',
  },
  {
    name: 'Benjamin Scott',
    picture: 'https://randomuser.me/api/portraits/men/11.jpg',
    say: 'Our company has seen unparalleled growth in credibility and visibility. Highly recommend this platform.',
    business_position: 'CEO of BrightPath Solutions',
  },
  {
    name: 'Emily Cooper',
    picture: 'https://randomuser.me/api/portraits/women/12.jpg',
    say: 'We’ve expanded our reach significantly since using this service. It’s been a key tool for our growth.',
    business_position: 'CEO at EcoSphere',
  },
  {
    name: 'Liam Roberts',
    picture: 'https://randomuser.me/api/portraits/men/12.jpg',
    say: 'Our team saved countless hours on PR while achieving incredible results. Highly efficient and effective.',
    business_position: 'Founder of BlueHorizon',
  },
  {
    name: 'Abigail Morgan',
    picture: 'https://randomuser.me/api/portraits/women/13.jpg',
    say: 'The results exceeded our expectations. We’re now featured regularly in industry publications.',
    business_position: 'VP of Marketing at ClearTech',
  },
  {
    name: 'Jackson Reed',
    picture: 'https://randomuser.me/api/portraits/men/13.jpg',
    say: 'This platform gave us the edge we needed to stand out in a crowded market.',
    business_position: 'CMO at BrightIdeas',
  },
  {
    name: 'Charlotte Turner',
    picture: 'https://randomuser.me/api/portraits/women/14.jpg',
    say: 'The ability to connect directly with media outlets has transformed how we share our story.',
    business_position: 'Public Relations Manager at GreenWave',
  },
  {
    name: 'Mason Hughes',
    picture: 'https://randomuser.me/api/portraits/men/14.jpg',
    say: 'We’ve seen a huge boost in traffic and engagement thanks to the media coverage we’ve received.',
    business_position: 'Founder of TechBridge',
  },
  {
    name: 'Ava Ramirez',
    picture: 'https://randomuser.me/api/portraits/women/15.jpg',
    say: 'It’s an incredible feeling to see our brand recognized on major platforms. This tool made it happen.',
    business_position: 'Creative Director at InspireCo',
  },
  {
    name: 'Logan Mitchell',
    picture: 'https://randomuser.me/api/portraits/men/15.jpg',
    say: 'From day one, we’ve seen immediate results in our PR campaigns. Couldn’t be happier.',
    business_position: 'Co-Founder of UrbanNest',
  },
  {
    name: 'Grace Walker',
    picture: 'https://randomuser.me/api/portraits/women/16.jpg',
    say: 'This platform is a PR powerhouse! It’s simple, effective, and produces real results.',
    business_position: 'CEO of BrightWorks',
  },
  {
    name: 'Ethan Harris',
    picture: 'https://randomuser.me/api/portraits/men/16.jpg',
    say: 'We’ve reached more people in the last month than we did in the past year. Truly outstanding!',
    business_position: 'Head of Marketing at FutureWave',
  },
  {
    name: 'Jessica Taylor',
    picture: 'https://randomuser.me/api/portraits/women/7.jpg',
    say: 'This service completely transformed how we handle PR. Our story is now being shared across major outlets.',
    business_position: 'Founder of UrbanLeaf',
  },
  {
    name: 'Matthew Johnson',
    picture: 'https://randomuser.me/api/portraits/men/7.jpg',
    say: 'Connecting with top-tier journalists has never been easier. This platform is a must-have for any startup.',
    business_position: 'CEO at BuildBright',
  },
  {
    name: 'Ashley Thompson',
    picture: 'https://randomuser.me/api/portraits/women/8.jpg',
    say: 'The user-friendly interface and powerful tools helped us achieve media attention like never before.',
    business_position: 'Marketing Manager at GlowTech',
  },
  {
    name: 'Ryan Walker',
    picture: 'https://randomuser.me/api/portraits/men/8.jpg',
    say: 'We saw instant results in our brand awareness after just a few weeks of using this service.',
    business_position: 'Founder of PeakInnovations',
  },
  {
    name: 'Sophia Adams',
    picture: 'https://randomuser.me/api/portraits/women/9.jpg',
    say: 'I can’t believe how much easier it is to gain media coverage with this platform. Truly groundbreaking!',
    business_position: 'CMO at TrendSetters',
  },
  {
    name: 'Ethan Carter',
    picture: 'https://randomuser.me/api/portraits/men/9.jpg',
    say: 'It’s been a game-changer for our business growth. The media exposure was far beyond what we expected.',
    business_position: 'Co-Founder of FutureTech Labs',
  },
  {
    name: 'Megan Parker',
    picture: 'https://randomuser.me/api/portraits/women/10.jpg',
    say: 'The team’s support and platform tools have been exceptional. We’ve reached audiences we never thought possible.',
    business_position: 'VP of Public Relations at CleanEnergyNow',
  },
  {
    name: 'William Davis',
    picture: 'https://randomuser.me/api/portraits/men/10.jpg',
    say: 'This is the best investment we’ve made for our brand. The impact has been tremendous!',
    business_position: 'Founder of FreshlyTech',
  },
  {
    name: 'Hannah Miller',
    picture: 'https://randomuser.me/api/portraits/women/11.jpg',
    say: 'From local exposure to national media, this platform delivered exactly what we needed.',
    business_position: 'Director of Communications at GreenFuture',
  },
  {
    name: 'Benjamin Scott',
    picture: 'https://randomuser.me/api/portraits/men/11.jpg',
    say: 'Our company has seen unparalleled growth in credibility and visibility. Highly recommend this platform.',
    business_position: 'CEO of BrightPath Solutions',
  },
  {
    name: 'Emily Cooper',
    picture: 'https://randomuser.me/api/portraits/women/12.jpg',
    say: 'We’ve expanded our reach significantly since using this service. It’s been a key tool for our growth.',
    business_position: 'CEO at EcoSphere',
  },
  {
    name: 'Liam Roberts',
    picture: 'https://randomuser.me/api/portraits/men/12.jpg',
    say: 'Our team saved countless hours on PR while achieving incredible results. Highly efficient and effective.',
    business_position: 'Founder of BlueHorizon',
  },
  {
    name: 'Abigail Morgan',
    picture: 'https://randomuser.me/api/portraits/women/13.jpg',
    say: 'The results exceeded our expectations. We’re now featured regularly in industry publications.',
    business_position: 'VP of Marketing at ClearTech',
  },
  {
    name: 'Jackson Reed',
    picture: 'https://randomuser.me/api/portraits/men/13.jpg',
    say: 'This platform gave us the edge we needed to stand out in a crowded market.',
    business_position: 'CMO at BrightIdeas',
  },
  {
    name: 'Charlotte Turner',
    picture: 'https://randomuser.me/api/portraits/women/14.jpg',
    say: 'The ability to connect directly with media outlets has transformed how we share our story.',
    business_position: 'Public Relations Manager at GreenWave',
  },
  {
    name: 'Mason Hughes',
    picture: 'https://randomuser.me/api/portraits/men/14.jpg',
    say: 'We’ve seen a huge boost in traffic and engagement thanks to the media coverage we’ve received.',
    business_position: 'Founder of TechBridge',
  },
  {
    name: 'Ava Ramirez',
    picture: 'https://randomuser.me/api/portraits/women/15.jpg',
    say: 'It’s an incredible feeling to see our brand recognized on major platforms. This tool made it happen.',
    business_position: 'Creative Director at InspireCo',
  },
  {
    name: 'Logan Mitchell',
    picture: 'https://randomuser.me/api/portraits/men/15.jpg',
    say: 'From day one, we’ve seen immediate results in our PR campaigns. Couldn’t be happier.',
    business_position: 'Co-Founder of UrbanNest',
  },
  {
    name: 'Grace Walker',
    picture: 'https://randomuser.me/api/portraits/women/16.jpg',
    say: 'This platform is a PR powerhouse! It’s simple, effective, and produces real results.',
    business_position: 'CEO of BrightWorks',
  },
  {
    name: 'Ethan Harris',
    picture: 'https://randomuser.me/api/portraits/men/16.jpg',
    say: 'We’ve reached more people in the last month than we did in the past year. Truly outstanding!',
    business_position: 'Head of Marketing at FutureWave',
  },
];